### ISSUE TITLE
Errors while building

### ISSUE THREAD

**Issue by noobbuild** [yshui/compton#240]
### Platform
Xubuntu 18.04 HWE Kernel 5.0.0.29 generic

### GPU, drivers, and screen setup
Intel integrated Graphics.

### Environment
Graphics:  Card: Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Integrated 
Display Server: x11 (X.Org 1.20.4 ) driver: modesetting Resolution: 1920x1080@60.00hz
OpenGL: renderer: Mesa DRI Intel HD Graphics 400 (Braswell)
version: 4.5 Mesa 19.0.8 Direct Render: Yes

### Compton version
none. Just couldn't build it. Getting lots of errors.

### Compton configuration:
```NA
// Paste your configuration here
```NA

### Steps of reproduction

1. sudo apt install libx11-dev libx11-xcb-dev libxext-dev x11proto-dev libx11-xcb-dev libxcb-damage0-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-render-util0-dev libxcb-render0-dev libxcb-randr0-dev libxcb-composite0-dev libxcb-image0-dev libxcb-present-dev libxcb-xinerama0-dev libpixman-1-dev libdbus-1-dev libconfig-dev libxdg-basedir-dev libgl1-mesa-dev libpcre3-dev libev-dev uthash-dev 

2.
git clone https://github.com/yshui/compton
cd compton
meson --buildtype=release . build
ninja -C build install

Result : Fails.

### Expected behavior
Should build.

### Current Behavior
Fails.
Log attached. 
Sorry, I'm a complete newcomer in this. I just did what was written in the front page and it wouldn't build anything.

[fail.txt](https://github.com/yshui/compton/files/3648300/fail.txt)

**Comment by jenav** [comment]
I was gonna report this same issue I'm having on openSUSE Leap 15.1 and 15.0. It doesn't happen on Tumbleweed.

`../src/win.c:1156:15: error: initializer element is not constant`

It was introduced in commit eecee130b8d7. 

According to my google search WIN_FLAGS_IMAGES_NONE is being used to initialize a static object and not every compiler implementation (or even implementation versions) supports other forms of 'constant', like #define or enum { N = 5 };

I actually tried changing the WIN_FLAGS_IMAGES_NONE declaration/definition to a #define and it compiled, but that's the furthest my skills can take me.

[build.log](https://github.com/yshui/compton/files/3648990/build.log)

**Comment by yshui** [comment]
@jenav that's what i would do too, can you open a PR for that?

**Comment by noobbuild** [comment]
I still cannot compile the build. Am I doing something wrong (like unmet dependencies) or something else like I'm too stupid to build this?

[build-fail2.txt](https://github.com/yshui/compton/files/3656326/build-fail2.txt)

**Comment by yshui** [comment]
@noobbuild did you remember to `git pull`?

**Comment by noobbuild** [comment]
yes. I deleted the entire compton dir and downloaded it again to be sure. 
maybe something is wrong in my system.

**Comment by yshui** [comment]
@noobbuild that's odd, do you have this line:
https://github.com/yshui/compton/blob/0c7a19fda67c05ad09cf4930b0615938a780f1da/src/win_defs.h#L94

in your codebase?

what is your distro, and what is the version of your compiler?

**Comment by noobbuild** [comment]
> @noobbuild that's odd, do you have this line:
> 
> https://github.com/yshui/compton/blob/0c7a19fda67c05ad09cf4930b0615938a780f1da/src/win_defs.h#L94
> 
> in your codebase?
> 
> what is your distro, and what is the version of your compiler?

I deleted that old compton folder along with the logs.
I used git to download a new copy of the code here. 

Yes, on line 94, i see this line in compton/src/win_defs.h:
`#define WIN_FLAGS_IMAGES_NONE (WIN_FLAGS_PIXMAP_NONE | WIN_FLAGS_SHADOW_NONE)`

Distro is Xubuntu 18.04. 
codebase means? I only installed build-essential from software repository along with meson and ninja.

compiler versions: 
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
meson 0.45.1
ninja 1.8.2

I think problem was with ninja. It gave an error again while building but then when I tried it again it did not throw any error. I think it did not refresh properly the first time?
Now the only error I get while trying to install is no permissions error.

`Installing src/compton to /usr/local/bin/compton
Traceback (most recent call last):
  File "/usr/bin/meson", line 26, in <module>
    sys.exit(main())
  File "/usr/bin/meson", line 23, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 318, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 274, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/share/meson/mesonbuild/scripts/meson_install.py", line 393, in run
    do_install(datafilename)
  File "/usr/share/meson/mesonbuild/scripts/meson_install.py", line 212, in do_install
    install_targets(d)
  File "/usr/share/meson/mesonbuild/scripts/meson_install.py", line 334, in install_targets
    do_copyfile(fname, outname)
  File "/usr/share/meson/mesonbuild/scripts/meson_install.py", line 126, in do_copyfile
    shutil.copyfile(from_file, to_file)
  File "/usr/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/local/bin/compton'
FAILED: meson-install 
/usr/bin/python3 /usr/bin/meson --internal install /home/vulcan/compton/build/meson-private/install.dat
ninja: build stopped: subcommand failed.
`
There is no /usr/local/bin/compton in my system.

**Comment by noobbuild** [comment]
I tried installing with sudo and it worked. No errors now. Thanks yshui and jenav for the help.

**Comment by yshui** [comment]
@noobbuild no problem
