### ISSUE TITLE
Build fails with "error: initializer element is not constant"

### ISSUE THREAD

**Issue by anowlcalledjosh** [yshui/compton#175]
### Platform
Ubuntu Desktop 18.04 amd64

### Compton version
`next`, i.e. 094f00a048f5d486cc0a17b9dd84e63eb6120ab5

### Current Behavior
```
[6/28] Compiling C object 'src/compton@exe/win.c.o'.
FAILED: src/compton@exe/win.c.o
cc  -Isrc/compton@exe -Isrc -I../src -Isubprojects/test.h -I../subprojects/test.h -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c11 -O2 -g '-DCOMPTON_VERSION="v6-rc1-137-g094f00a04"' -D_GNU_SOURCE -DHAS_STDC_PREDEF_H -Wall -Wextra -Wno-unused-parameter -Wnonnull -Wshadow -Wno-type-limits -Wimplicit-fallthrough -Wno-unknown-warning-option -Wno-missing-braces -Wconversion -DCONFIG_LIBCONFIG -DCONFIG_REGEX_PCRE -DCONFIG_REGEX_PCRE_JIT -DCONFIG_OPENGL -DGL_GLEXT_PROTOTYPES -DCONFIG_DBUS -MD -MQ 'src/compton@exe/win.c.o' -MF 'src/compton@exe/win.c.o.d' -o 'src/compton@exe/win.c.o' -c ../src/win.c
../src/win.c: In function ‘fill_win’:
../src/win.c:1059:22: error: initializer element is not constant
      .opacity_prop = OPAQUE,
                      ^~~~~~
../src/win.c:1059:22: note: (near initialization for ‘win_def.opacity_prop’)
```

I tried to bisect, and it appears to have been introduced in 16ea51bbc1ef4604abdeb1c638d6379b930a1610 (which changed `OPAQUE` from a `#define` to a `const opacity_t`); a409913c5 builds fine after cherry-picking 18a62537e, but 16ea51bbc does not.

**Comment by yshui** [comment]
What's your compiler version?

**Comment by anowlcalledjosh** [comment]
Meson says:

    Native C compiler: cc (gcc 7.4.0 "cc (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0")

**Comment by yshui** [comment]
Apparently the behavior of gcc changed since 8.1: https://godbolt.org/z/FYGZcx

Guess I will have to change it back to a define.
